name: Terraform Integration Tests
on:
  workflow_run:
    workflows: ["Terraform Unit Tests"]
    types:
      - completed

jobs:
  terraform-integration:
    # Run If Unit Test Pass
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Terraform init
      - name: Initialize Terraform
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Version
        run: terraform version

      - name: List Module Folders
        run: ls -l Modules/

      - name: Confirm Environments File
        run: ls -l environments/staging.tfvars

      - name: Terraform Plan
        run: terraform plan -var-file=environments/staging.tfvars -var="ssh_public_key_path=${{ secrets.VMSS_SSH_PUBLIC_KEY }}" -out=tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      # Setup TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

      # Azure TFLint Config
      - name: Configure Azure TFLint rules
        run: |
          cat <<EOF > .tflint.hcl
          config { format = "compact" }

          plugin "azurerm" {
            enabled = true
            source  = "github.com/terraform-linters/tflint-ruleset-azurerm"
            version = "0.27.0"
          }

          rule "terraform_unused_declarations" {
            enabled = true
            level   = "WARNING"
          }
          EOF

      # TF Init
      - name: Initialize TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Run TFLint
      - name: Run TFLint
        run: tflint -f compact || true
