name: Terraform Plan Validation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Static Analysis"]
    types:
      - completed

jobs:
  Terraform-Staging-Plan-Validation:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Module Folders
        run: ls -l Modules/

      - name: Confirm Staging Environment File
        run: |
          ENV_FILE=environments/staging/staging.tfvars
          if [ ! -f "$ENV_FILE" ]; then
            echo "Staging TFVARS File Missing"
            exit 1
          fi
          echo "Found Staging.tfvars"

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Terraform init
      - name: Initialize Terraform
        run: terraform -chdir=environments/staging init -backend=false
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      # Terraform Version
      - name: Terraform Version
        run: terraform version

      # Terraform Plan
      - name: Terraform Staging Plan
        run: |
          terraform -chdir=environments/staging plan \
            -refresh=false \
            -var-file=staging.tfvars \
            -var="ssh_public_key_path=${{ secrets.VMSS_SSH_PUBLIC_KEY }}" \
            -out=tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
