name: Terraform Static Analysis

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/modules/**"
      - ".github/workflows/**"
      - "**/*.md"
    branches: [dev]

  pull_request:
    branches: [dev]

jobs:
  terraform-format-validate:
    runs-on: ubuntu-latest
    env:
      TF_LOG: "ERROR"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Module Folders
        run: ls -l Modules/

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

        # TF Version
      - name: Terraform Version
        run: terraform version

        # Format
      - name: Terraform FMT
        run: terraform fmt -check -recursive

        # Initialize Terraform Without Backend
      - name: Initialize Terraform
        run: terraform init -backend=false

        # Validation
      - name: Terraform Validate
        run: terraform validate

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    needs: terraform-format-validate

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

        # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

        # Initialize Terraform Without Backend
      - name: Terraform Init
        run: terraform init -backend=false

        # Setup TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

        # Azure TFLint config
      - name: Configure Azure TFLint Rules
        run: |
          cat <<EOF > .tflint.hcl
          config {
            format = "compact"
          }

          plugin "azurerm" {
            enabled = true
            source  = "github.com/terraform-linters/tflint-ruleset-azurerm"
            version = "0.27.0"
          }

          rule "terraform_unused_declarations" {
            enabled = true
            level   = "WARNING"
          }
          EOF

        # TF Init
      - name: Initialize TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Run RFLint
      - name: Run TFLint
        run: tflint -f compact || true

  checkov-security-analysis:
    name: Checkov Security Analysis
    runs-on: ubuntu-latest
    needs: tflint

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      #  Run Checkov
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          check: CKV_AZURE_*
          soft_fail: false
          output_format: cli
