name: Terraform Production Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Destroy Terraform Production Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Module Folders
        run: ls -l Modules/

      # Confirm Production TFvars Exists
      - name: Confirm Production Environment File
        run: |
          ENV_FILE=environments/production.tfvars
          if [ ! -f "$ENV_FILE" ]; then
            echo "Production tfvars file not found"
            exit 1
          fi
          echo "Found Production.tfvars"

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Load Backend Values With Production.tfvars
      - name: Load Backend Variables
        run: |
          ENV_FILE=environments/production.tfvars

          RG=$(grep -E '^rg_name' "$ENV_FILE" | awk -F'=' '{print $2}' | xargs)
          SA=$(grep -E '^storage_account_name' "$ENV_FILE" | awk -F'=' '{print $2}' | xargs)
          CONTAINER=$(grep -E '^storage_container_name' "$ENV_FILE" | awk -F'=' '{print $2}' | xargs)
          KEY=$(grep -E '^state_key' "$ENV_FILE" | awk -F'=' '{print $2}' | xargs)

          echo "RG_NAME=$RG" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
          echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
          echo "STATE_KEY=$KEY" >> $GITHUB_ENV

      # Initialize Terraform Using Production Terraform.tfstate*
      - name: Initialize Terraform (Remote Backend)
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ env.RG_NAME }}" \
            -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.STATE_KEY }}" \
            -backend-config="sas_token=${{ secrets.AZURE_SAS_TOKEN }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Version
        run: terraform version

      # Destroy Resources In Production State
      - name: Terraform Destroy (Production)
        run: |
          terraform destroy \
            -auto-approve \
            -var-file=environments/production.tfvars \
            -var="ssh_public_key_path=${{ secrets.VMSS_SSH_PUBLIC_KEY }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
