name: Terraform Production Deployment
on:
  workflow_dispatch:

jobs:
  Terraform-Production-Deployment:
    name: Create Production Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Module Folders
        run: ls -l Modules/

      - name: Confirm Production Variables
        run: ls -l environments/production/production.tfvars

      - name: Clear Terraform Cache
        run: |
          find . -name ".terraform" -type d -exec rm -rf {} +
          rm -f .terraform.lock.hcl tfplan

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Load Production Backend Variables
      - name: Load Backend Variables
        run: |
          RG=$(grep -E '^resource_group_name' environments/production/production.tfvars | awk -F'=' '{print $2}' | xargs)
          SA=$(grep -E '^storage_account_name' environments/production/production.tfvars | awk -F'=' '{print $2}' | xargs)
          CONTAINER=$(grep -E '^container_name' environments/production/production.tfvars | awk -F'=' '{print $2}' | xargs)
          KEY=$(grep -E '^state_key' environments/production.tfvars | awk -F'=' '{print $2}' | xargs)

          RG="${RG//$'\r'/}"
          SA="${SA//$'\r'/}"
          CONTAINER="${CONTAINER//$'\r'/}"
          KEY="${KEY//$'\r'/}"

          echo "RG_NAME=$RG" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
          echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
          echo "STATE_KEY=$KEY" >> $GITHUB_ENV

      # Confirm Production Variables
      - name: Confirm Backend Variables
        run: |
          echo "resource_group_name=$RG_NAME"
          echo "STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME"
          echo "STORAGE_CONTAINER_NAME=$STORAGE_CONTAINER_NAME"
          echo "STATE_KEY=$STATE_KEY"

      # Terraform Init
      - name: Initialize Terraform
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=${{ env.RG_NAME }}" \
            -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.STATE_KEY }}" \
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

        # Terraform Version
      - name: Terraform Version
        run: terraform version

      # Terraform Plan
      - name: Production Terraform Plan
        run: terraform plan -var-file=environments/production/production.tfvars -var="ssh_public_key_path=${{ secrets.VMSS_SSH_PUBLIC_KEY }}" -out=tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      # Terraform Apply
      - name: Production Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: List Terraform State Resources
        run: terraform state list
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
