name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy-production:
    name: Destroy Terraform Production Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Module Folders
        run: ls -l Modules/

      # Confirm Production TFvars Exists
      - name: Confirm Production Environment File
        run: |
          ENV_FILE=environments/production/production.tfvars
          if [ ! -f "$ENV_FILE" ]; then
            echo "Production TFVARS File Missing"
            exit 1
          fi
          echo "Found Production.tfvars"

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Production Backend Variables
      - name: Load Production Remote State Variables
        run: |
          RG=$(grep -E '^\s*resource_group_name\s*=' environments/production/production.tfvars | awk -F'=' '{print $2}' | xargs)
          SA=$(grep -E '^\s*storage_account_name\s*=' environments/production/production.tfvars | awk -F'=' '{print $2}' | xargs)
          CONTAINER=$(grep -E '^\s*storage_container_name\s*=' environments/production/production.tfvars | awk -F'=' '{print $2}' | xargs)
          KEY=$(grep -E '^\s*state_key\s*=' environments/production/production.tfvars | awk -F'=' '{print $2}' | xargs)


          RG="${RG//$'\r'/}"
          SA="${SA//$'\r'/}"
          CONTAINER="${CONTAINER//$'\r'/}"
          KEY="${KEY//$'\r'/}"


          echo "RG_NAME=$RG" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
          echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
          echo "STATE_KEY=$KEY" >> $GITHUB_ENV

        # Confirm Production Backend Variables
      - name: Confirm Backend Variables Values
        run: |
          echo "resource_group_name=$RG_NAME"
          echo "STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME"
          echo "STORAGE_CONTAINER_NAME=$STORAGE_CONTAINER_NAME"
          echo "STATE_KEY=$STATE_KEY"

      # Initialize Terraform Using Production State
      - name: Initialize Production Terraform State
        working-directory: environments/production
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=${{ env.RG_NAME }}" \
            -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.STATE_KEY }}" \
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Version
        run: terraform version

      # Destroy Resources In Production
      - name: Terraform Destroy Production Resources
        working-directory: environments/production
        run: terraform destroy -var-file=production.tfvars -var="ssh_public_key_path=${{ secrets.VMSS_SSH_PUBLIC_KEY }}" -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  terraform-destroy-backend:
    name: Destroy Terraform Production Backend Resources
    runs-on: ubuntu-latest
    needs: terraform-destroy-production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Production Backend Variables
      - name: Load Backend Remote State Variables
        run: |
          RG=$(grep -E '^\s*resource_group_name\s*=' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)
          SA=$(grep -E '^\s*storage_account_name\s*=' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)
          CONTAINER=$(grep -E '^\s*storage_container_name\s*=' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)
          KEY=$(grep -E '^\s*state_key\s*=' environments/backend/backend.tfvars | awk -F'=' '{print $2}' | xargs)


          RG="${RG//$'\r'/}"
          SA="${SA//$'\r'/}"
          CONTAINER="${CONTAINER//$'\r'/}"
          KEY="${KEY//$'\r'/}"


          echo "RG_NAME=$RG" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT_NAME=$SA" >> $GITHUB_ENV
          echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
          echo "STATE_KEY=$KEY" >> $GITHUB_ENV

        # Confirm Production Backend Variables
      - name: Confirm Backend Variables Values
        run: |
          echo "resource_group_name=$RG_NAME"
          echo "STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME"
          echo "STORAGE_CONTAINER_NAME=$STORAGE_CONTAINER_NAME"
          echo "STATE_KEY=$STATE_KEY"

        # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Initialize Terraform Using Backend State
      - name: Initialize Backend Terraform State
        working-directory: environments/backend
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=${{ env.RG_NAME }}" \
            -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ env.STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.STATE_KEY }}" \
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Version
        run: terraform version

      # Destroy Resources In Production
      - name: Terraform Destroy Backend Resources
        working-directory: environments/backend
        run: terraform destroy -var-file=backend.tfvars -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
