name: Terraform Unit Tests

on:
  push:
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/modules/**"
      - ".github/workflows/**"
      - "**/*.md"
    branches: [dev]

  pull_request:
    branches: [dev]

jobs:
  Terraform-Unit-Test:
    runs-on: ubuntu-latest
    env:
      TF_LOG: "ERROR"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Module Folders
        run: ls -l Modules/

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Version
        run: terraform version

      - name: Terraform FMT
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # Setup TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6

      # Azure TFLint config
      - name: Configure Azure TFLint Rules
        run: |
          cat <<EOF > .tflint.hcl
          config {
            format = "compact"
          }

          plugin "azurerm" {
            enabled = true
            source  = "github.com/terraform-linters/tflint-ruleset-azurerm"
            version = "0.27.0"
          }

          rule "terraform_unused_declarations" {
              enabled = true
              level   = "WARNING"
            }
          EOF

      # TF Init
      - name: Initialize TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Run RFLint
      - name: Run TFLint
        run: tflint -f compact || true
